
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppDocSearch: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppDocSearch.vue")['default']
export const AppFooter: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppFooter.vue")['default']
export const AppHeader: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeader.vue")['default']
export const AppHeaderDialog: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderDialog.vue")['default']
export const AppHeaderLogo: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderLogo.vue")['default']
export const AppHeaderNavigation: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderNavigation.vue")['default']
export const AppLayout: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppLayout.vue")['default']
export const AppLoadingBar: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppLoadingBar.vue")['default']
export const AppSearch: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppSearch.vue")['default']
export const AppSocialIcons: typeof import("../node_modules/@nuxt-themes/docus/components/app/AppSocialIcons.vue")['default']
export const DocumentDrivenNotFound: typeof import("../node_modules/@nuxt-themes/docus/components/app/DocumentDrivenNotFound.vue")['default']
export const Ellipsis: typeof import("../node_modules/@nuxt-themes/docus/components/app/Ellipsis.vue")['default']
export const Logo: typeof import("../node_modules/@nuxt-themes/docus/components/app/Logo.vue")['default']
export const ThemeSelect: typeof import("../node_modules/@nuxt-themes/docus/components/app/ThemeSelect.vue")['default']
export const DocsAside: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsAside.vue")['default']
export const DocsAsideTree: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsAsideTree.vue")['default']
export const DocsPageBottom: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPageBottom.vue")['default']
export const DocsPageLayout: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPageLayout.vue")['default']
export const DocsPrevNext: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPrevNext.vue")['default']
export const DocsToc: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsToc.vue")['default']
export const DocsTocLinks: typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsTocLinks.vue")['default']
export const EditOnLink: typeof import("../node_modules/@nuxt-themes/docus/components/docs/EditOnLink.vue")['default']
export const SourceLink: typeof import("../node_modules/@nuxt-themes/docus/components/docs/SourceLink.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseCodeInline.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseP.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseUl.vue")['default']
export const ProseCodeCopyButton: typeof import("../node_modules/@nuxt-themes/typography/components/ProseCodeCopyButton.vue")['default']
export const Alert: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Alert.vue")['default']
export const Badge: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Badge.vue")['default']
export const ButtonLink: typeof import("../node_modules/@nuxt-themes/elements/components/globals/ButtonLink.vue")['default']
export const Callout: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Callout.vue")['default']
export const CodeBlock: typeof import("../node_modules/@nuxt-themes/elements/components/globals/CodeBlock.vue")['default']
export const CodeGroup: typeof import("../node_modules/@nuxt-themes/elements/components/globals/CodeGroup.vue")['default']
export const Container: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Container.vue")['default']
export const CopyButton: typeof import("../node_modules/@nuxt-themes/elements/components/globals/CopyButton.vue")['default']
export const List: typeof import("../node_modules/@nuxt-themes/elements/components/globals/List.vue")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt-themes/elements/components/globals/NuxtImg.vue")['default']
export const Props: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Props.vue")['default']
export const Sandbox: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Sandbox.vue")['default']
export const TabsHeader: typeof import("../node_modules/@nuxt-themes/elements/components/globals/TabsHeader.vue")['default']
export const Terminal: typeof import("../node_modules/@nuxt-themes/elements/components/globals/Terminal.vue")['default']
export const VideoPlayer: typeof import("../node_modules/@nuxt-themes/elements/components/globals/VideoPlayer.vue")['default']
export const IconCodeSandBox: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconCodeSandBox.vue")['default']
export const IconDocus: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconDocus.vue")['default']
export const IconNuxt: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxt.vue")['default']
export const IconNuxtContent: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtContent.vue")['default']
export const IconNuxtLabs: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtLabs.vue")['default']
export const IconNuxtStudio: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtStudio.vue")['default']
export const IconStackBlitz: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconStackBlitz.vue")['default']
export const IconVueTelescope: typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconVueTelescope.vue")['default']
export const BlockHero: typeof import("../node_modules/@nuxt-themes/elements/components/landing/BlockHero.vue")['default']
export const Card: typeof import("../node_modules/@nuxt-themes/elements/components/landing/Card.vue")['default']
export const CardGrid: typeof import("../node_modules/@nuxt-themes/elements/components/landing/CardGrid.vue")['default']
export const VoltaBoard: typeof import("../node_modules/@nuxt-themes/elements/components/volta/VoltaBoard.vue")['default']
export const ComponentPlayground: typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlayground.vue")['default']
export const ComponentPlaygroundData: typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundData.vue")['default']
export const ComponentPlaygroundProps: typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundProps.vue")['default']
export const ComponentPlaygroundSlots: typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundSlots.vue")['default']
export const ComponentPlaygroundTokens: typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundTokens.vue")['default']
export const PreviewLayout: typeof import("../node_modules/@nuxt-themes/elements/components/meta/PreviewLayout.vue")['default']
export const TokensPlayground: typeof import("../node_modules/@nuxt-themes/elements/components/meta/TokensPlayground.vue")['default']
export const ContentPreviewMode: typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppDocSearch: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppDocSearch.vue")['default']>
export const LazyAppFooter: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeader.vue")['default']>
export const LazyAppHeaderDialog: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderDialog.vue")['default']>
export const LazyAppHeaderLogo: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderLogo.vue")['default']>
export const LazyAppHeaderNavigation: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppHeaderNavigation.vue")['default']>
export const LazyAppLayout: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppLayout.vue")['default']>
export const LazyAppLoadingBar: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppLoadingBar.vue")['default']>
export const LazyAppSearch: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppSearch.vue")['default']>
export const LazyAppSocialIcons: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/AppSocialIcons.vue")['default']>
export const LazyDocumentDrivenNotFound: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/DocumentDrivenNotFound.vue")['default']>
export const LazyEllipsis: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/Ellipsis.vue")['default']>
export const LazyLogo: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/Logo.vue")['default']>
export const LazyThemeSelect: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/app/ThemeSelect.vue")['default']>
export const LazyDocsAside: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsAside.vue")['default']>
export const LazyDocsAsideTree: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsAsideTree.vue")['default']>
export const LazyDocsPageBottom: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPageBottom.vue")['default']>
export const LazyDocsPageLayout: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPageLayout.vue")['default']>
export const LazyDocsPrevNext: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsPrevNext.vue")['default']>
export const LazyDocsToc: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsToc.vue")['default']>
export const LazyDocsTocLinks: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/DocsTocLinks.vue")['default']>
export const LazyEditOnLink: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/EditOnLink.vue")['default']>
export const LazySourceLink: LazyComponent<typeof import("../node_modules/@nuxt-themes/docus/components/docs/SourceLink.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseCode.vue")['default']>
export const LazyProseCodeInline: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseCodeInline.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseP.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/global/ProseUl.vue")['default']>
export const LazyProseCodeCopyButton: LazyComponent<typeof import("../node_modules/@nuxt-themes/typography/components/ProseCodeCopyButton.vue")['default']>
export const LazyAlert: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Alert.vue")['default']>
export const LazyBadge: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Badge.vue")['default']>
export const LazyButtonLink: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/ButtonLink.vue")['default']>
export const LazyCallout: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Callout.vue")['default']>
export const LazyCodeBlock: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/CodeBlock.vue")['default']>
export const LazyCodeGroup: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/CodeGroup.vue")['default']>
export const LazyContainer: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Container.vue")['default']>
export const LazyCopyButton: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/CopyButton.vue")['default']>
export const LazyList: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/List.vue")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/NuxtImg.vue")['default']>
export const LazyProps: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Props.vue")['default']>
export const LazySandbox: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Sandbox.vue")['default']>
export const LazyTabsHeader: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/TabsHeader.vue")['default']>
export const LazyTerminal: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/Terminal.vue")['default']>
export const LazyVideoPlayer: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/globals/VideoPlayer.vue")['default']>
export const LazyIconCodeSandBox: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconCodeSandBox.vue")['default']>
export const LazyIconDocus: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconDocus.vue")['default']>
export const LazyIconNuxt: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxt.vue")['default']>
export const LazyIconNuxtContent: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtContent.vue")['default']>
export const LazyIconNuxtLabs: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtLabs.vue")['default']>
export const LazyIconNuxtStudio: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconNuxtStudio.vue")['default']>
export const LazyIconStackBlitz: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconStackBlitz.vue")['default']>
export const LazyIconVueTelescope: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/icons/IconVueTelescope.vue")['default']>
export const LazyBlockHero: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/landing/BlockHero.vue")['default']>
export const LazyCard: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/landing/Card.vue")['default']>
export const LazyCardGrid: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/landing/CardGrid.vue")['default']>
export const LazyVoltaBoard: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/volta/VoltaBoard.vue")['default']>
export const LazyComponentPlayground: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlayground.vue")['default']>
export const LazyComponentPlaygroundData: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundData.vue")['default']>
export const LazyComponentPlaygroundProps: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundProps.vue")['default']>
export const LazyComponentPlaygroundSlots: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundSlots.vue")['default']>
export const LazyComponentPlaygroundTokens: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/ComponentPlaygroundTokens.vue")['default']>
export const LazyPreviewLayout: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/PreviewLayout.vue")['default']>
export const LazyTokensPlayground: LazyComponent<typeof import("../node_modules/@nuxt-themes/elements/components/meta/TokensPlayground.vue")['default']>
export const LazyContentPreviewMode: LazyComponent<typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']>
export const LazyContentDoc: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']>
export const LazyContentList: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']>
export const LazyContentNavigation: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']>
export const LazyContentQuery: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']>
export const LazyContentRenderer: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyContentRendererMarkdown: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']>
export const LazyContentSlot: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']>
export const LazyDocumentDrivenEmpty: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']>
export const LazyMarkdown: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyMDC: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']>
export const LazyIconCSS: LazyComponent<typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
